ruby:
    gatekeeper_app_path: /root/kalibro_gatekeeper
    mezuro_app_path: /root/mezuro
phantomjs:
    install_path: /opt/phantomjs
    version: 1.9.7
ports:
    - 22
    - 8080
    - 5432
    - 8081
    - 3000
files:
    - Dockerfile.erb
    - mezuro_start.sh.erb
    - mezuro_setup.sh.erb
    - gatekeeper_setup.sh.erb
    - gatekeeper_start.sh.erb
features:
    - kalibro
    - gatekeeper
    - mezuro
    - phantomjs

