gatekeeper:
    install_path: /home/mezuro/kalibro_gatekeeper
mezuro:
    install: true
    install_path: /home/mezuro/mezuro
phantomjs:
    install: true
    download_path: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.7-linux-x86_64.tar.bz2
    install_path: /opt/phantomjs
ports:
    - 8081
    - 3000
files:
    - Dockerfile.erb
    - mezuro_start.sh.erb
    - mezuro_setup.sh.erb
    - gatekeeper_setup.sh.erb
    - gatekeeper_start.sh.erb


